In [ ]:
# PREPROCESAMIENTO - PARTICIONES DE DATOS
import numpy as np

# Leer datos
X=np.load('/content/particiones-datos-balanceados.npz')['X']
Y=np.load('/content/particiones-datos-balanceados.npz')['Y']

print(X.shape)
print(Y.shape)

(20, 3)
(20,)


In [ ]:
X

array([[-0.75275929,  1.11852895, -7.5592353 ],
       [ 2.70428584, -3.60506139, -0.0964618 ],
       [ 1.39196365, -2.07855351, -9.31222958],
       [ 0.59195091, -1.33638157,  8.18640804],
       [-2.06388816, -0.43930016, -4.82440037],
       [-2.06403288,  2.85175961,  3.25044569],
       [-2.65149833, -3.00326218, -3.76577848],
       [ 2.19705687,  0.14234438,  0.40136042],
       [ 0.60669007,  0.92414569,  0.93420559],
       [ 1.24843547, -4.53549587, -6.30291089],
       [-2.87649303,  1.07544852,  9.39169256],
       [ 2.81945911, -3.29475876,  5.50265647],
       [ 1.99465584, -4.34948407,  8.78997883],
       [-1.72596534,  4.48885537,  7.89654701],
       [-1.9090502 ,  4.65632033,  1.95799958],
       [-1.89957294,  3.08397348,  8.4374847 ],
       [-1.17454654, -1.95386231, -8.23014996],
       [ 0.14853859, -4.02327886, -6.08034275],
       [-0.40832989,  1.84233027, -9.09545422],
       [-1.25262516, -0.59847506, -3.49339338]])

In [ ]:
Y

array([1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 0, 1, 1, 0, 0, 0, 0])

In [ ]:
from sklearn.model_selection import train_test_split

# Particion en datos de entrenamiento, validacion y prueba
x_train, x_resto, y_train, y_resto = train_test_split(X,Y, test_size=0.4, random_state=123)
x_val, x_test, y_val, y_test = train_test_split(x_resto, y_resto, test_size=0.5, random_state=321)

In [ ]:
print("Tamanos: ")
print("\tDataset original: ", X.shape, Y.shape)
print("\tDataset entrenamieno: ", x_train.shape, y_train.shape)
print("\tDataset validaciones: ", x_val.shape, y_val.shape)
print("\tDataset pruebas: ", x_test.shape, y_test.shape)

Tamanos: 
	Dataset original:  (20, 3) (20,)
	Dataset entrenamieno:  (12, 3) (12,)
	Dataset validaciones:  (4, 3) (4,)
	Dataset pruebas:  (4, 3) (4,)


In [ ]:
#Vic: Las proporciones permiten saber si los datasets estan balanceados
print("Proporciones categorias (0s/1s): ")
print(f"\tDataset original: {np.sum(Y==0)/len(Y)}/{np.sum(Y==1)/len(Y)}")
print(f"\tDataset entrenamiento: {np.sum(y_train==0)/len(y_train)}/{np.sum(y_train==1)/len(y_train)}")
print(f"\tDataset validacion: {np.sum(y_val==0)/len(y_val)}/{np.sum(y_val==1)/len(y_val)}")
print(f"\tDataset pruebas: {np.sum(y_test==0)/len(y_test)}/{np.sum(y_test==1)/len(y_test)}")

Proporciones categorias (0s/1s): 
	Dataset original: 0.55/0.45
	Dataset entrenamiento: 0.5833333333333334/0.4166666666666667
	Dataset validacion: 0.5/0.5
	Dataset pruebas: 0.5/0.5


In [ ]:
# Leer datos
X=np.load('/content/particiones-datos-desbalanceados.npz')['X']
Y=np.load('/content/particiones-datos-desbalanceados.npz')['Y']

print(X)
print(Y)

[[-0.75275929  1.11852895 -7.5592353 ]
 [ 2.70428584 -3.60506139 -0.0964618 ]
 [ 1.39196365 -2.07855351 -9.31222958]
 [ 0.59195091 -1.33638157  8.18640804]
 [-2.06388816 -0.43930016 -4.82440037]
 [-2.06403288  2.85175961  3.25044569]
 [-2.65149833 -3.00326218 -3.76577848]
 [ 2.19705687  0.14234438  0.40136042]
 [ 0.60669007  0.92414569  0.93420559]
 [ 1.24843547 -4.53549587 -6.30291089]
 [-2.87649303  1.07544852  9.39169256]
 [ 2.81945911 -3.29475876  5.50265647]
 [ 1.99465584 -4.34948407  8.78997883]
 [-1.72596534  4.48885537  7.89654701]
 [-1.9090502   4.65632033  1.95799958]
 [-1.89957294  3.08397348  8.4374847 ]
 [-1.17454654 -1.95386231 -8.23014996]
 [ 0.14853859 -4.02327886 -6.08034275]
 [-0.40832989  1.84233027 -9.09545422]
 [-1.25262516 -0.59847506 -3.49339338]]
[1 0 1 0 1 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print('Proporciones categorias (0s/1s) set desbalanceados: ')
print(f'\t{np.sum(Y==0)/len(Y)}/{np.sum(Y==1)/len(Y)}')

Proporciones categorias (0s/1s) set desbalanceados: 
	0.8/0.2


In [ ]:
# Particion en entrenamiento, validacion y prueba
x_train, x_resto, y_train, y_resto=train_test_split(X,Y, test_size=0.4, random_state=20,stratify=Y)
x_val, x_test, y_val, y_test=train_test_split(x_resto, y_resto, test_size=0.5, random_state=10, stratify=y_resto)

In [ ]:
print("Tamanos: ")
print("\tDataset original: ", X.shape, Y.shape)
print("\tDataset entrenamieno: ", x_train.shape, y_train.shape)
print("\tDataset validaciones: ", x_val.shape, y_val.shape)
print("\tDataset pruebas: ", x_test.shape, y_test.shape)

Tamanos: 
	Dataset original:  (20, 3) (20,)
	Dataset entrenamieno:  (12, 3) (12,)
	Dataset validaciones:  (4, 3) (4,)
	Dataset pruebas:  (4, 3) (4,)


In [ ]:
#Vic: Las proporciones permiten saber si los datasets estan balanceados
print("Proporciones categorias (0s/1s): ")
print(f"\tDataset original: {np.sum(Y==0)/len(Y)}/{np.sum(Y==1)/len(Y)}")
print(f"\tDataset entrenamiento: {np.sum(y_train==0)/len(y_train)}/{np.sum(y_train==1)/len(y_train)}")
print(f"\tDataset validacion: {np.sum(y_val==0)/len(y_val)}/{np.sum(y_val==1)/len(y_val)}")
print(f"\tDataset pruebas: {np.sum(y_test==0)/len(y_test)}/{np.sum(y_test==1)/len(y_test)}")

Proporciones categorias (0s/1s): 
	Dataset original: 0.8/0.2
	Dataset entrenamiento: 0.8333333333333334/0.16666666666666666
	Dataset validacion: 0.75/0.25
	Dataset pruebas: 0.75/0.25


In [ ]:
# PREPROCESAMIENTO - TRASNFORMACION DE DATOS
# Transforma los datos: escalar, codificacion, reducir columnas
# fit_transform() para transformar set entrenamiento
# transform() para transformar set validacion y pruebas

In [ ]:
print(f'x_train: {x_train.min(axis=0)}/{x_train.max(axis=0)}')
print(f'x_val: {x_val.min(axis=0)}/{x_val.max(axis=0)}')
print(f'x_test: {x_test.min(axis=0)}/{x_test.max(axis=0)}')

x_train: [-2.87649303 -4.34948407 -9.31222958]/[2.81945911 3.08397348 9.39169256]
x_val: [-2.06388816 -0.43930016 -9.09545422]/[-0.40832989  4.65632033  7.89654701]
x_test: [-2.65149833 -4.53549587 -8.23014996]/[2.19705687 0.14234438 0.40136042]


In [ ]:
#Paso 1 - Crear la instancia
# Solo se debe escalar el dataset de entrenamiento
# Los otros dataset se escalan apartir del dataset de entrenamiento
from sklearn.preprocessing import MinMaxScaler
scaler=MinMaxScaler(feature_range=(-1,1))

In [ ]:
# Escalamiento
x_train_s=scaler.fit_transform(x_train)

In [ ]:
print(f'Minimos de "x_train": {x_train.min(axis=0)}')
print(f'Minimos calculador por el escalador": {scaler.data_min_}')
print('-'*50)
print(f'Maximos de "x_train": {x_train.max(axis=0)}')
print(f'Maximos calculador por el escalador": {scaler.data_max_}')

Minimos de "x_train": [-2.87649303 -4.34948407 -9.31222958]
Minimos calculador por el escalador": [-2.87649303 -4.34948407 -9.31222958]
--------------------------------------------------
Maximos de "x_train": [2.81945911 3.08397348 9.39169256]
Maximos calculador por el escalador": [2.81945911 3.08397348 9.39169256]


In [ ]:
print(f'x_train_s: {x_train_s.min(axis=0)}/{x_train_s.max(axis=0)}')

x_train_s: [-1. -1. -1.]/[1. 1. 1.]


In [ ]:
#Los dataset de validacion y pruebas se escalan con los datos minimos y maximos almacenados en scaler. Esos datos fueron obtenidos del set de entrenamiento

# Escalamiento
x_val_s=scaler.transform(x_val)
x_test_s=scaler.transform(x_test)

In [ ]:
print(f'x_val_s: {x_val_s.min(axis=0)}/{x_val_s.max(axis=0)}')
print(f'x_test_s: {x_test_s.min(axis=0)}/{x_test_s.max(axis=0)}')

x_val_s: [-0.71467286  0.05204984 -0.97682033]/[-0.1333624   1.42304589  0.84012492]
x_test_s: [-0.92099839 -1.05004718 -0.88429383]/[0.78145805 0.20854351 0.03866878]


In [ ]:
# CREAR, ENTRENAR Y VALIDAR EL MODELO: (32:12)
# En scikitlearn un modelo se conoce como un estimador

#1. Crear un instancia del modelo
#2. Entrenar el modelo con el dataset de entrenamiento. fit() = ajustar el modelo
#3. Validar el modelo con los dataset de entrenamiento y validacion. score() = puntuar el modelo
#4. Predecir con modelo y dataset de prueba. predict() = predecir con el modelo y score() = puntuar el modelo

In [ ]:
#1 Crear una instancia del modelo

#Creacion, entrenamiento y validacion del modelo
from sklearn.ensemble import RandomForestClassifier
bosque=RandomForestClassifier()

In [ ]:
#2. Entrenar el modelo con el dataset de entrenamiento. fit() = ajustar el modelo
bosque.fit(x_train, y_train)

RandomForestClassifier()

In [ ]:
#3. Validar el modelo con los dataset de entrenamiento y validacion. score() = puntuar el modelo
bosque.score

<bound method ClassifierMixin.score of RandomForestClassifier()>

In [ ]:
#4. Probar el model con el dataset de prueba. predict() = predecir con el modelo y score() = puntuar el modelo
print(f'Puntuacion promedio entrenamiento: {bosque.score(x_train, y_train)}')
print(f'Puntuacion promedio validacion: {bosque.score(x_val, y_val)}')

Puntuacion promedio entrenamiento: 1.0
Puntuacion promedio validacion: 0.5


In [ ]:
bosque.score(x_test, y_test)

0.5

In [ ]:
#4. Predecir con modelo y dataset de prueba. predict() = predecir con el modelo y score() = puntuar el modelo

#Generacion de predicciones
y_pred=bosque.predict(x_test)

In [ ]:
print(f'Categorias reales: {y_test}')
print(f'Çategorias predichas: {y_pred}')

Categorias reales: [1 0 0 0]
Çategorias predichas: [0 0 1 0]


In [ ]:
# PIPELINES
# Los pipelines permite crear modelos de machine leanring con codigo mas compacto
# Combinacion de transformadores y estimadores en un solo objeto, una pipeline

In [ ]:
# Con pipelines
from sklearn.pipeline import Pipeline
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from sklearn.ensemble import RandomForestClassifier

In [ ]:
# Leer datos
X=np.load('/content/particiones-datos-balanceados.npz')['X']
Y=np.load('/content/particiones-datos-balanceados.npz')['Y']

In [ ]:
# Particion en entrenamiento, validacion y pruebas
x_train, x_resto, y_train, y_resto=train_test_split(X,Y, test_size=0.4, random_state=123)
x_val, x_test, y_val, y_test=train_test_split(x_resto, y_resto, test_size=0.5, random_state=321)

In [ ]:
# Instanciar la pipeline
pipeline = Pipeline([
    ('scaler', MinMaxScaler(feature_range=(-1,1))),
    ('classifier', RandomForestClassifier())
])

In [ ]:
# Entrenar la pipeline
pipeline.fit(x_train, y_train)

Pipeline(steps=[('scaler', MinMaxScaler(feature_range=(-1, 1))),
                ('classifier', RandomForestClassifier())])

In [ ]:
print(pipeline.score(x_test, y_test))

0.25
